/-
tools/fg_emit_pins.lean -- GENERATED by tools/gen_fg_emit_pins.py.
Do not edit by hand; regenerate and let the teeth compare bytes.

Level B pins: each entry transcribes one corpus reading ONCE as an
EReading datum; `emitProp` (the in-module reference emitter) must
render it to EXACTLY the proposition bytes the shipped Python compiler
emitted for the same reading (theorem wrapper stripped) -- discharged
by kernel rfl when this file elaborates appended to
tools/FgReflect.lean.  The Python tooth (tests/test_fg_emit_pins.py)
pins the same strings against a live compiler run, closing the loop:
emitter bytes == pin bytes == compiler bytes.  The second example per
entry routes the SAME datum through toReading into compile_preserves,
so the pinned surface and the level-A statement share one source.
-/

namespace FgReflect

set_option maxHeartbeats 400000

/-- specs/mathsources/readings/01_dvd_reflexive.json (theorem dvd_reflexive). -/
def pin_01_dvd_reflexive : EReading :=
  { segs := [
      { ex := false, vars := [("n", "Int")] }],
    names := ["n"],
    hyps := [],
    concl := (Pd.pdvd (Tm.tvar 0) (Tm.tvar 0)),
    concls := [] }

example : emitProp pin_01_dvd_reflexive =
    "∀ (n : Int), (n ∣ n)" := rfl

example (env : Nat -> Int) :
    readingDenote (toReading pin_01_dvd_reflexive) env <->
    denoteStmt env (compileR (toReading pin_01_dvd_reflexive)) :=
  compile_preserves _ _

/-- specs/mathsources/readings/02_one_divides_all.json (theorem one_divides_all). -/
def pin_02_one_divides_all : EReading :=
  { segs := [
      { ex := false, vars := [("n", "Int")] }],
    names := ["n"],
    hyps := [],
    concl := (Pd.pdvd (Tm.lit 1) (Tm.tvar 0)),
    concls := [] }

example : emitProp pin_02_one_divides_all =
    "∀ (n : Int), (1 ∣ n)" := rfl

example (env : Nat -> Int) :
    readingDenote (toReading pin_02_one_divides_all) env <->
    denoteStmt env (compileR (toReading pin_02_one_divides_all)) :=
  compile_preserves _ _

/-- specs/mathsources/readings/04_even_plus_even.json (theorem even_plus_even). -/
def pin_04_even_plus_even : EReading :=
  { segs := [
      { ex := false, vars := [("a", "Int"), ("b", "Int")] }],
    names := ["a", "b"],
    hyps := [(Pd.peven (Tm.tvar 0)), (Pd.peven (Tm.tvar 1))],
    concl := (Pd.peven (Tm.add (Tm.tvar 0) (Tm.tvar 1))),
    concls := [] }

example : emitProp pin_04_even_plus_even =
    "∀ (a : Int) (b : Int), (Even a) → (Even b) → (Even (a + b))" := rfl

example (env : Nat -> Int) :
    readingDenote (toReading pin_04_even_plus_even) env <->
    denoteStmt env (compileR (toReading pin_04_even_plus_even)) :=
  compile_preserves _ _

/-- specs/mathsources/readings/43_larger_integer_exists.json (theorem larger_integer_exists). -/
def pin_43_larger_integer_exists : EReading :=
  { segs := [
      { ex := false, vars := [("n", "Int")] },
      { ex := true, vars := [("m", "Int")] }],
    names := ["m", "n"],
    hyps := [],
    concl := (Pd.plt (Tm.tvar 1) (Tm.tvar 0)),
    concls := [] }

example : emitProp pin_43_larger_integer_exists =
    "∀ (n : Int), ∃ (m : Int), (n < m)" := rfl

example (env : Nat -> Int) :
    readingDenote (toReading pin_43_larger_integer_exists) env <->
    denoteStmt env (compileR (toReading pin_43_larger_integer_exists)) :=
  compile_preserves _ _

/-- specs/mathsources/readings/63_gap_witness.json (theorem gap_witness). -/
def pin_63_gap_witness : EReading :=
  { segs := [
      { ex := false, vars := [("a", "Int"), ("b", "Int")] },
      { ex := true, vars := [("d", "Int")] }],
    names := ["a", "b", "d"],
    hyps := [(Pd.ple (Tm.tvar 0) (Tm.tvar 1))],
    concl := (Pd.peq (Tm.add (Tm.tvar 0) (Tm.tvar 2)) (Tm.tvar 1)),
    concls := [] }

example : emitProp pin_63_gap_witness =
    "∀ (a : Int) (b : Int), ∃ (d : Int), (a ≤ b) → ((a + d) = b)" := rfl

example (env : Nat -> Int) :
    readingDenote (toReading pin_63_gap_witness) env <->
    denoteStmt env (compileR (toReading pin_63_gap_witness)) :=
  compile_preserves _ _

/-- specs/mathsources/readings/64_pos_pred_witness.json (theorem pos_pred_witness). -/
def pin_64_pos_pred_witness : EReading :=
  { segs := [
      { ex := false, vars := [("n", "Int")] },
      { ex := true, vars := [("m", "Int")] }],
    names := ["m", "n"],
    hyps := [(Pd.plt (Tm.lit 0) (Tm.tvar 1))],
    concl := (Pd.pand (Pd.ple (Tm.lit 0) (Tm.tvar 0)) (Pd.plt (Tm.tvar 0) (Tm.tvar 1))),
    concls := [] }

example : emitProp pin_64_pos_pred_witness =
    "∀ (n : Int), ∃ (m : Int), (0 < n) → ((0 ≤ m) ∧ (m < n))" := rfl

example (env : Nat -> Int) :
    readingDenote (toReading pin_64_pos_pred_witness) env <->
    denoteStmt env (compileR (toReading pin_64_pos_pred_witness)) :=
  compile_preserves _ _

/-- specs/mathsources/readings/65_double_witness.json (theorem double_witness). -/
def pin_65_double_witness : EReading :=
  { segs := [
      { ex := false, vars := [("n", "Int")] },
      { ex := true, vars := [("m", "Int")] }],
    names := ["m", "n"],
    hyps := [],
    concl := (Pd.peq (Tm.add (Tm.tvar 0) (Tm.tvar 0)) (Tm.add (Tm.tvar 1) (Tm.tvar 1))),
    concls := [] }

example : emitProp pin_65_double_witness =
    "∀ (n : Int), ∃ (m : Int), ((m + m) = (n + n))" := rfl

example (env : Nat -> Int) :
    readingDenote (toReading pin_65_double_witness) env <->
    denoteStmt env (compileR (toReading pin_65_double_witness)) :=
  compile_preserves _ _

/-- specs/mathsources/readings/66_sum_exists.json (theorem sum_exists). -/
def pin_66_sum_exists : EReading :=
  { segs := [
      { ex := false, vars := [("a", "Int"), ("b", "Int")] },
      { ex := true, vars := [("s", "Int")] }],
    names := ["a", "b", "s"],
    hyps := [],
    concl := (Pd.peq (Tm.tvar 2) (Tm.add (Tm.tvar 0) (Tm.tvar 1))),
    concls := [] }

example : emitProp pin_66_sum_exists =
    "∀ (a : Int) (b : Int), ∃ (s : Int), (s = (a + b))" := rfl

example (env : Nat -> Int) :
    readingDenote (toReading pin_66_sum_exists) env <->
    denoteStmt env (compileR (toReading pin_66_sum_exists)) :=
  compile_preserves _ _

/-- specs/mathsources/readings/67_nat_pred_witness.json (theorem nat_pred_witness). -/
def pin_67_nat_pred_witness : EReading :=
  { segs := [
      { ex := false, vars := [("n", "Nat")] },
      { ex := true, vars := [("m", "Nat")] }],
    names := ["m", "n"],
    hyps := [(Pd.ple (Tm.lit 1) (Tm.tvar 1))],
    concl := (Pd.peq (Tm.add (Tm.tvar 0) (Tm.lit 1)) (Tm.tvar 1)),
    concls := [] }

example : emitProp pin_67_nat_pred_witness =
    "∀ (n : Nat), ∃ (m : Nat), (1 ≤ n) → ((m + 1) = n)" := rfl

example (env : Nat -> Int) :
    readingDenote (toReading pin_67_nat_pred_witness) env <->
    denoteStmt env (compileR (toReading pin_67_nat_pred_witness)) :=
  compile_preserves _ _

/-- specs/mathsources/readings/68_between_witness.json (theorem between_witness). -/
def pin_68_between_witness : EReading :=
  { segs := [
      { ex := false, vars := [("a", "Int"), ("b", "Int")] },
      { ex := true, vars := [("c", "Int")] }],
    names := ["a", "b", "c"],
    hyps := [(Pd.ple (Tm.tvar 0) (Tm.tvar 1))],
    concl := (Pd.pand (Pd.ple (Tm.tvar 0) (Tm.tvar 2)) (Pd.ple (Tm.tvar 2) (Tm.tvar 1))),
    concls := [] }

example : emitProp pin_68_between_witness =
    "∀ (a : Int) (b : Int), ∃ (c : Int), (a ≤ b) → ((a ≤ c) ∧ (c ≤ b))" := rfl

example (env : Nat -> Int) :
    readingDenote (toReading pin_68_between_witness) env <->
    denoteStmt env (compileR (toReading pin_68_between_witness)) :=
  compile_preserves _ _

/-- specs/mathsources/readings/69_upper_neighbor.json (theorem upper_neighbor). -/
def pin_69_upper_neighbor : EReading :=
  { segs := [
      { ex := false, vars := [("n", "Int")] },
      { ex := true, vars := [("m", "Int")] }],
    names := ["m", "n"],
    hyps := [],
    concl := (Pd.pand (Pd.ple (Tm.tvar 1) (Tm.tvar 0)) (Pd.ple (Tm.tvar 0) (Tm.add (Tm.tvar 1) (Tm.lit 1)))),
    concls := [] }

example : emitProp pin_69_upper_neighbor =
    "∀ (n : Int), ∃ (m : Int), ((n ≤ m) ∧ (m ≤ (n + 1)))" := rfl

example (env : Nat -> Int) :
    readingDenote (toReading pin_69_upper_neighbor) env <->
    denoteStmt env (compileR (toReading pin_69_upper_neighbor)) :=
  compile_preserves _ _

end FgReflect
