#!/usr/bin/env python3
"""The live session brief: current mining-loop state, DERIVED, never authored.

The orientation problem a static CLAUDE.md cannot solve: the 24/7 flywheel
moves state every cycle (corpus grows, purchases land, pins re-baseline), so
any prose snapshot decays.  This tool derives the brief from the committed
artifacts the loop already maintains -- it CANNOT go stale, because it is
computed:

  * era + counts      <- specs/mathsources/registration.json (re-baselined
                         every growth cycle by law, tooth-checked against
                         the primary artifacts)
  * portfolio + queue <- results/census_portfolio.json (regenerated by the
                         flywheel's own re-census step)
  * mining/admission  <- specs/mathsources/operators/{proposed,admitted.json}
  * purchase queue    <- results/purchase_frontier.json (the §4 queue with
                         live census prices and statuses read off the tree,
                         so "what is next to buy" stops being recollection)
  * supply verdict    <- results/supply_status.json (whether ANY loop has
                         material to consume, and by which path -- the line
                         that separates an idle machine from a wedged one)
  * plan state        <- PLAN_FRAGMENT.md §1 verbatim (house law: "update
                         every cycle" -- the plan's own discipline keeps it
                         current; this tool just surfaces it)
  * lane state        <- git HEAD (whether the last commit carries a Lean
                         lane tag, i.e. whether a verdict is pending)

Running this is a driver session's FIRST COMMAND (PLAN_FRAGMENT §3.1), so
the session starts ORIENTED instead of exploring.  Stdlib-only and fast: it
must work even before the pinned dependency closure is present.

REPORTS state; decides nothing.  Missing artifacts degrade to a named line,
never a crash -- a half-built tree still gets a brief.
"""
from __future__ import annotations

import glob
import json
import os
import re
import subprocess
import sys

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _load(relpath: str):
    try:
        with open(os.path.join(_ROOT, relpath)) as fh:
            return json.load(fh)
    except (OSError, ValueError) as e:
        return {"_unavailable": f"{relpath}: {e.__class__.__name__}"}


def _plan_section_1() -> str:
    """PLAN_FRAGMENT.md §1 verbatim (the update-every-cycle state block)."""
    try:
        text = open(os.path.join(_ROOT, "PLAN_FRAGMENT.md")).read()
    except OSError:
        return "(PLAN_FRAGMENT.md unavailable)"
    m = re.search(r"^## 1\..*?(?=^## )", text, re.M | re.S)
    return m.group(0).rstrip() if m else "(PLAN_FRAGMENT.md has no §1 block)"


def _git(*args: str) -> str:
    try:
        return subprocess.run(["git", *args], cwd=_ROOT, capture_output=True,
                              text=True, timeout=10).stdout.strip()
    except Exception:
        return ""


def build_brief() -> str:
    lines = ["=" * 72,
             "SESSION BRIEF (derived; regenerate: python3 tools/session_brief.py)",
             "=" * 72]

    reg = _load("specs/mathsources/registration.json")
    if "_unavailable" not in reg:
        g = reg.get("governed_exogenous", {})
        lines += [
            f"ERA: {reg.get('era', '?')}",
            f"  sources {reg.get('n_top_level_sources', '?')} | governed "
            f"readings {g.get('n_readings', '?')} "
            f"(certified {g.get('n_certified', '?')}) | waves "
            f"0..{reg.get('final_wave', '?')}",
        ]
    else:
        lines.append(f"ERA: {reg['_unavailable']}")

    port = _load("results/census_portfolio.json")
    if "_unavailable" not in port:
        v = port.get("verdicts", {})
        queue = [(r["corpus"], len(r["attempt_candidates"]))
                 for r in port.get("corpora", []) if r["attempt_candidates"]]
        lines += [
            f"PORTFOLIO: {port.get('n_corpora', '?')} corpora, "
            f"{port.get('n_nodes', '?')} nodes | attempt-candidates "
            f"{v.get('attempt-candidate', 0)}, out-of-fragment "
            f"{v.get('out-of-fragment', 0)}, no-signal {v.get('no-signal', 0)}",
            "  C2 queue: " + (", ".join(f"{c}={n}" for c, n in queue) or "empty"),
        ]
    else:
        lines.append(f"PORTFOLIO: {port['_unavailable']}")

    proposed = len(glob.glob(os.path.join(
        _ROOT, "specs", "mathsources", "operators", "proposed", "*.json")))
    admitted = _load("specs/mathsources/operators/admitted.json")
    n_admitted = ("?" if "_unavailable" in admitted else len(admitted))
    lines.append(f"OPERATORS: {proposed} proposals staged, "
                 f"{n_admitted} admitted (incl. grandfathered)")

    pf = _load("results/purchase_frontier.json")
    if "_unavailable" not in pf:
        rows = pf.get("purchases", [])
        by_status: dict = {}
        for r in rows:
            by_status[r["status"]] = by_status.get(r["status"], 0) + 1
        opens = [r for r in rows if r["status"] == "open"]
        nxt = (f"{opens[0]['purchase_id']} ({opens[0]['bill_class']})"
               if opens else "none open")
        lines.append(
            f"PURCHASES: {by_status.get('purchased', 0)} purchased, "
            f"{by_status.get('open', 0)} open, "
            f"{by_status.get('trust-root', 0)} trust-root, "
            f"{by_status.get('parked', 0)} parked | next open: {nxt}")
    else:
        lines.append(f"PURCHASES: {pf['_unavailable']}")

    # The line that tells IDLE from WEDGED.  Every count above reports a
    # loop; none of them reports whether any loop has material to consume,
    # and "nothing to do" read identically to "nothing it CAN do" until this
    # verdict existed.  It is loud on purpose: a session that opens on a
    # blocked supply should spend itself on an exit, not on a re-survey.
    sup = _load("results/supply_status.json")
    if "_unavailable" not in sup:
        rows = [r for r in sup.get("paths", []) if isinstance(r, dict)]
        counts = ", ".join(f"{r.get('path', '?')}={r.get('count', '?')}"
                           for r in rows)
        lines += [
            f"SUPPLY: {sup.get('verdict', '?')}",
            f"  ready {sup.get('frontier_ready', {}).get('count', '?')} | "
            + (counts or "no supply paths reported"),
        ]
        # The selection route, DERIVED -- the "cycle immediately after a
        # purchase" rule lived in session memory and cycle 23 proved that a
        # session cannot be trusted to know it is that cycle; this line is
        # computed from the committed ledger-vs-registry state and the
        # DRIVER prompt binds to it by name.
        sel = sup.get("next_selection")
        if isinstance(sel, dict):
            route = sel.get("route", "unknown")
            if route == "unblocked":
                lines.append(
                    f"NEXT-SELECTION: unblocked -- "
                    f"{sel.get('awaiting_subjects', '?')} paid subjects await "
                    "the unblock run; BEFORE any --ready consumption, run "
                    "per signal:")
                for sig in sel.get("signals", []):
                    lines.append("    python3 tools/intake_from_frontier.py "
                                 f"--unblocked {sig} --take 8")
            elif route == "ready":
                lines.append("NEXT-SELECTION: ready (consume the ready list "
                             "in frontier order)")
            elif route == "refill":
                lines.append("NEXT-SELECTION: refill (ready empty, nothing "
                             "awaiting unblock -- the supply verdict names "
                             "the exits)")
            else:
                lines.append("NEXT-SELECTION: unknown (an input did not "
                             "read; regenerate supply_status first)")
        verdict = str(sup.get("verdict", ""))
        if verdict.startswith("supply-blocked"):
            lines += [
                "  ** SUPPLY BLOCKED: no driver can make progress unattended.",
                "  ** The paths named in the verdict ARE the exits -- take one;",
                "  ** an idle cycle here is a wedged cycle, not a quiet one.",
            ]
        elif verdict.startswith("supply-unknown"):
            lines.append("  ** SUPPLY UNKNOWN: an input above did not read -- "
                         "regenerate before trusting any idle reading.")
    else:
        lines.append(f"SUPPLY: {sup['_unavailable']} "
                     "(regenerate: python3 tools/supply_status.py)")

    head = _git("log", "-1", "--format=%h %s")
    lines.append(f"HEAD: {head or '(git unavailable)'}")
    if re.search(r"\[lean-(ci|fast|fresh)\]", head):
        lines += [
            "  ** LANE VERDICT PENDING: the last commit fired a Lean lane.",
            "  ** Rule 1 (PLAN_FRAGMENT S3.1): read its CI conclusion FIRST",
            "  ** (one Actions query, this branch, newest run -- keep the",
            "  ** query minimal; full listings overflow a session context).",
            "  ** Red lane => the fix IS this cycle's work.",
        ]
    else:
        lines.append("  no Lean lane tag on HEAD; no verdict gate before "
                     "Lean-free work")

    lines += [
        "-" * 72,
        _plan_section_1(),
        "-" * 72,
        "TOOLKIT (committed; never rebuild in-session):",
        "  tools/session_brief.py       this brief",
        "  tools/intake_corpus.py       corpus intake (fetch->extract->meta)",
        "  tools/census_portfolio.py    re-census every corpus",
        "  tools/regen_downstream.py    downstream artifact DAG (--from resumes)",
        "  tools/purchase_frontier.py   the S4 purchase queue, priced + status-derived",
        "  tools/supply_status.py       can the loop move, and by which path",
        "  tools/measure_cluster_key.py --print-reregistration  next era's block",
        "  specs/mathsources/registration.json  the ONE corpus-growth re-baseline",
        "PROTOCOL: PLAN_FRAGMENT.md S3.1 (lane-verdict first; Lean-last; "
        "corpus track never blocks)",
        "INVARIANTS: CLAUDE.md (stable router; trust anti-list; test subsets)",
        "=" * 72,
    ]
    return "\n".join(lines)


def main(argv=None) -> int:
    print(build_brief())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
