#!/usr/bin/env python3
"""The live session brief: current mining-loop state, DERIVED, never authored.

The orientation problem a static CLAUDE.md cannot solve: the 24/7 flywheel
moves state every cycle (corpus grows, purchases land, pins re-baseline), so
any prose snapshot decays.  This tool derives the brief from the committed
artifacts the loop already maintains -- it CANNOT go stale, because it is
computed:

  * era + counts      <- specs/mathsources/registration.json (re-baselined
                         every growth cycle by law, tooth-checked against
                         the primary artifacts)
  * portfolio + queue <- results/census_portfolio.json (regenerated by the
                         flywheel's own re-census step)
  * mining/admission  <- specs/mathsources/operators/{proposed,admitted.json}
  * plan state        <- PLAN_FRAGMENT.md §1 verbatim (house law: "update
                         every cycle" -- the plan's own discipline keeps it
                         current; this tool just surfaces it)
  * lane state        <- git HEAD (whether the last commit carries a Lean
                         lane tag, i.e. whether a verdict is pending)

Running this is a driver session's FIRST COMMAND (PLAN_FRAGMENT §3.1), so
the session starts ORIENTED instead of exploring.  Stdlib-only and fast: it
must work even before the pinned dependency closure is present.

REPORTS state; decides nothing.  Missing artifacts degrade to a named line,
never a crash -- a half-built tree still gets a brief.
"""
from __future__ import annotations

import glob
import json
import os
import re
import subprocess
import sys

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _load(relpath: str):
    try:
        with open(os.path.join(_ROOT, relpath)) as fh:
            return json.load(fh)
    except (OSError, ValueError) as e:
        return {"_unavailable": f"{relpath}: {e.__class__.__name__}"}


def _plan_section_1() -> str:
    """PLAN_FRAGMENT.md §1 verbatim (the update-every-cycle state block)."""
    try:
        text = open(os.path.join(_ROOT, "PLAN_FRAGMENT.md")).read()
    except OSError:
        return "(PLAN_FRAGMENT.md unavailable)"
    m = re.search(r"^## 1\..*?(?=^## )", text, re.M | re.S)
    return m.group(0).rstrip() if m else "(PLAN_FRAGMENT.md has no §1 block)"


def _git(*args: str) -> str:
    try:
        return subprocess.run(["git", *args], cwd=_ROOT, capture_output=True,
                              text=True, timeout=10).stdout.strip()
    except Exception:
        return ""


def build_brief() -> str:
    lines = ["=" * 72,
             "SESSION BRIEF (derived; regenerate: python3 tools/session_brief.py)",
             "=" * 72]

    reg = _load("specs/mathsources/registration.json")
    if "_unavailable" not in reg:
        g = reg.get("governed_exogenous", {})
        lines += [
            f"ERA: {reg.get('era', '?')}",
            f"  sources {reg.get('n_top_level_sources', '?')} | governed "
            f"readings {g.get('n_readings', '?')} "
            f"(certified {g.get('n_certified', '?')}) | waves "
            f"0..{reg.get('final_wave', '?')}",
        ]
    else:
        lines.append(f"ERA: {reg['_unavailable']}")

    port = _load("results/census_portfolio.json")
    if "_unavailable" not in port:
        v = port.get("verdicts", {})
        queue = [(r["corpus"], len(r["attempt_candidates"]))
                 for r in port.get("corpora", []) if r["attempt_candidates"]]
        lines += [
            f"PORTFOLIO: {port.get('n_corpora', '?')} corpora, "
            f"{port.get('n_nodes', '?')} nodes | attempt-candidates "
            f"{v.get('attempt-candidate', 0)}, out-of-fragment "
            f"{v.get('out-of-fragment', 0)}, no-signal {v.get('no-signal', 0)}",
            "  C2 queue: " + (", ".join(f"{c}={n}" for c, n in queue) or "empty"),
        ]
    else:
        lines.append(f"PORTFOLIO: {port['_unavailable']}")

    proposed = len(glob.glob(os.path.join(
        _ROOT, "specs", "mathsources", "operators", "proposed", "*.json")))
    admitted = _load("specs/mathsources/operators/admitted.json")
    n_admitted = ("?" if "_unavailable" in admitted else len(admitted))
    lines.append(f"OPERATORS: {proposed} proposals staged, "
                 f"{n_admitted} admitted (incl. grandfathered)")

    head = _git("log", "-1", "--format=%h %s")
    lines.append(f"HEAD: {head or '(git unavailable)'}")
    if re.search(r"\[lean-(ci|fast|fresh)\]", head):
        lines += [
            "  ** LANE VERDICT PENDING: the last commit fired a Lean lane.",
            "  ** Rule 1 (PLAN_FRAGMENT S3.1): read its CI conclusion FIRST",
            "  ** (one Actions query, this branch, newest run -- keep the",
            "  ** query minimal; full listings overflow a session context).",
            "  ** Red lane => the fix IS this cycle's work.",
        ]
    else:
        lines.append("  no Lean lane tag on HEAD; no verdict gate before "
                     "Lean-free work")

    lines += [
        "-" * 72,
        _plan_section_1(),
        "-" * 72,
        "TOOLKIT (committed; never rebuild in-session):",
        "  tools/session_brief.py       this brief",
        "  tools/intake_corpus.py       corpus intake (fetch->extract->meta)",
        "  tools/census_portfolio.py    re-census every corpus",
        "  tools/regen_downstream.py    downstream artifact DAG (--from resumes)",
        "  tools/measure_cluster_key.py --print-reregistration  next era's block",
        "  specs/mathsources/registration.json  the ONE corpus-growth re-baseline",
        "PROTOCOL: PLAN_FRAGMENT.md S3.1 (lane-verdict first; Lean-last; "
        "corpus track never blocks)",
        "INVARIANTS: CLAUDE.md (stable router; trust anti-list; test subsets)",
        "=" * 72,
    ]
    return "\n".join(lines)


def main(argv=None) -> int:
    print(build_brief())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
